USE [Media]
GO

/****** Object:  Table [MP3].[ALBUM]    Script Date: 3/16/2017 08:03:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[ALBUM](
	[ALBUM_ID] [numeric](38, 0) IDENTITY(5711,1) NOT NULL,
	[ARTIST_ID] [numeric](38, 0) NOT NULL,
	[ALBUM_NAME] [varchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_ALBUM] PRIMARY KEY CLUSTERED 
(
	[ALBUM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [MP3].[ALBUM] ADD  CONSTRAINT [DF_ALBUM_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [MP3].[ALBUM]  WITH CHECK ADD  CONSTRAINT [FK_ALBUM_ARTIST] FOREIGN KEY([ARTIST_ID])
REFERENCES [MP3].[ARTIST] ([ARTIST_ID])
GO

ALTER TABLE [MP3].[ALBUM] CHECK CONSTRAINT [FK_ALBUM_ARTIST]
GO

