USE [Media]
GO

/****** Object:  Table [MP3].[ARTIST]    Script Date: 4/13/2017 23:17:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[ARTIST](
	[ARTIST_ID] [numeric](38, 0) IDENTITY(2831,1) NOT NULL,
	[ARTIST_NAME] [varchar](255) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_ARTIST] PRIMARY KEY CLUSTERED 
(
	[ARTIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [MP3].[ARTIST] ADD  CONSTRAINT [DF_ARTIST_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

