USE [Media]
GO

/****** Object:  Table [MP3].[LOG]    Script Date: 3/16/2017 08:04:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[LOG](
	[LOG_ID] [numeric](38, 0) IDENTITY(1061,1) NOT NULL,
	[ENTRY] [varchar](500) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [MP3].[LOG] ADD  CONSTRAINT [DF_LOG_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

