USE [Media]
GO

/****** Object:  Table [MP3].[SONG]    Script Date: 4/13/2017 23:17:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[SONG](
	[SONG_ID] [numeric](38, 0) IDENTITY(17050,1) NOT NULL,
	[ARTIST_ID] [numeric](38, 0) NULL,
	[ALBUM_ID] [numeric](38, 0) NULL,
	[SONG_TITLE] [varchar](255) NOT NULL,
	[ALBUM_ART] [varbinary](max) NULL,
	[LYRICS] [varchar](4000) NULL,
	[YEAR] [varchar](25) NULL,
	[GENRE] [varchar](100) NULL,
	[TRACK_NUM] [varchar](50) NULL,
	[DISC_NUM] [varchar](50) NULL,
	[ALBUM_ART_FLAG] [bit] NOT NULL,
	[LYRICS_FLAG] [bit] NOT NULL,
	[ITUNES_FLAG] [bit] NOT NULL,
	[ID3V1_FLAG] [bit] NOT NULL,
	[ID3V1_ARTIST] [varchar](255) NULL,
	[ID3V1_ALBUM] [varchar](255) NULL,
	[ID3V1_TITLE] [varchar](255) NULL,
	[ID3V2_FLAG] [bit] NOT NULL,
	[ID3V2_ARTIST] [varchar](255) NULL,
	[ID3V2_ALBUM] [varchar](255) NULL,
	[ID3V2_TITLE] [varchar](255) NULL,
	[UPDATE_TAGS_FLAG] [bit] NOT NULL,
	[NEW_ALBUM] [varchar](255) NULL,
	[NEW_TITLE] [varchar](255) NULL,
	[NEW_TRACK_NUM] [numeric](38, 0) NULL,
	[NEW_GENRE] [varchar](100) NULL,
	[FILENAME] [varchar](255) NULL,
	[ABS_FILE_PATH] [varchar](1000) NULL,
	[REL_FILE_PATH] [varchar](1000) NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
	[RECOMMEND_FLAG] [bit] NOT NULL,
	[UPDATE_FILE_FLAG] [bit] NOT NULL,
	[OLD_ART] [varbinary](max) NULL,
	[FAVORITES_FLAG] [bit] NOT NULL,
	[VIDEO_PATH] [varchar](255) NULL,
	[FILE_SIZE] [numeric](38, 0) NULL,
	[DURATION] [varchar](50) NULL,
	[SAMPLE_RATE] [numeric](38, 0) NULL,
	[BITRATE] [numeric](38, 0) NULL,
	[BACK_COVER] [varbinary](max) NULL,
	[ARTIST_IMAGE] [varbinary](max) NULL,
	[BAND] [varbinary](max) NULL,
	[PLAY_COUNT] [numeric](1, 0) NOT NULL,
	[DOWNLOAD_COUNT] [numeric](1, 0) NOT NULL,
	[NEW_ARTIST] [varchar](50) NULL,
	[COMMENTS] [varchar](4000) NULL,
	[COMPOSER] [varchar](500) NULL,
	[CONDUCTOR] [varchar](500) NULL,
 CONSTRAINT [PK_SONG] PRIMARY KEY CLUSTERED 
(
	[SONG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_ALBUM_ART_FLAG]  DEFAULT ((1)) FOR [ALBUM_ART_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_LYRICS_FLAG]  DEFAULT ((0)) FOR [LYRICS_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_ITUNES_FLAG]  DEFAULT ((0)) FOR [ITUNES_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_ID3V1_FLAG]  DEFAULT ((1)) FOR [ID3V1_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_ID3V2_FLAG]  DEFAULT ((1)) FOR [ID3V2_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_UPDATE_TAGS_FLAG]  DEFAULT ((0)) FOR [UPDATE_TAGS_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_RECOMMEND_FLAG]  DEFAULT ((0)) FOR [RECOMMEND_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_UPDATE_FILE_FLAG]  DEFAULT ((0)) FOR [UPDATE_FILE_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_FAVORITES_FLAG]  DEFAULT ((0)) FOR [FAVORITES_FLAG]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_PLAY_COUNT]  DEFAULT ((0)) FOR [PLAY_COUNT]
GO

ALTER TABLE [MP3].[SONG] ADD  CONSTRAINT [DF_SONG_DOWNLOAD_COUNT]  DEFAULT ((0)) FOR [DOWNLOAD_COUNT]
GO

ALTER TABLE [MP3].[SONG]  WITH CHECK ADD  CONSTRAINT [FK_SONG_ALBUM] FOREIGN KEY([ALBUM_ID])
REFERENCES [MP3].[ALBUM] ([ALBUM_ID])
GO

ALTER TABLE [MP3].[SONG] CHECK CONSTRAINT [FK_SONG_ALBUM]
GO

