USE [Media]
GO

/****** Object:  Table [MP3].[USER_PLAYLIST]    Script Date: 4/13/2017 23:18:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[USER_PLAYLIST](
	[SONG_ID] [numeric](38, 0) NOT NULL,
	[USER_SECURITY_ID] [numeric](38, 0) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[NAME] [varchar](255) NULL,
 CONSTRAINT [PK_MP3.USER_PLAYLIST] PRIMARY KEY CLUSTERED 
(
	[SONG_ID] ASC,
	[USER_SECURITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [MP3].[USER_PLAYLIST] ADD  CONSTRAINT [DF_USER_PLAYLIST_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [MP3].[USER_PLAYLIST]  WITH CHECK ADD  CONSTRAINT [FK_USER_PLAYLIST_SONG] FOREIGN KEY([SONG_ID])
REFERENCES [MP3].[SONG] ([SONG_ID])
GO

ALTER TABLE [MP3].[USER_PLAYLIST] CHECK CONSTRAINT [FK_USER_PLAYLIST_SONG]
GO

ALTER TABLE [MP3].[USER_PLAYLIST]  WITH CHECK ADD  CONSTRAINT [FK_USER_PLAYLIST_USER_SECURITY] FOREIGN KEY([USER_SECURITY_ID])
REFERENCES [MP3].[USER_SECURITY] ([USER_SECURITY_ID])
GO

ALTER TABLE [MP3].[USER_PLAYLIST] CHECK CONSTRAINT [FK_USER_PLAYLIST_USER_SECURITY]
GO

