USE [Media]
GO

/****** Object:  Table [MP3].[USER_SECURITY]    Script Date: 4/13/2017 23:18:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[USER_SECURITY](
	[USER_SECURITY_ID] [numeric](38, 0) IDENTITY(2,1) NOT NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[PASSWORD] [varchar](4000) NULL,
	[LOCKED_FLAG] [bit] NOT NULL,
	[ACTIVE_FLAG] [bit] NOT NULL,
	[LAST_LOGIN_DATE] [datetime] NULL,
	[LOGIN_FAILURE_COUNT] [numeric](38, 0) NOT NULL,
	[LAST_FAILURE_DATE] [datetime] NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
	[ADMIN_FLAG] [bit] NOT NULL,
	[PREV_TO_LAST_LOGIN_DATE] [datetime] NULL,
 CONSTRAINT [PK_USER_SECURITY] PRIMARY KEY CLUSTERED 
(
	[USER_SECURITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [MP3].[USER_SECURITY] ADD  CONSTRAINT [DF_USER_SECURITY_LOCKED_FLAG]  DEFAULT ((0)) FOR [LOCKED_FLAG]
GO

ALTER TABLE [MP3].[USER_SECURITY] ADD  CONSTRAINT [DF_USER_SECURITY_ACTIVE_FLAG]  DEFAULT ((1)) FOR [ACTIVE_FLAG]
GO

ALTER TABLE [MP3].[USER_SECURITY] ADD  CONSTRAINT [DF_USER_SECURITY_LOGIN_FAILURE_COUNT]  DEFAULT ((0)) FOR [LOGIN_FAILURE_COUNT]
GO

ALTER TABLE [MP3].[USER_SECURITY] ADD  CONSTRAINT [DF_USER_SECURITY_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [MP3].[USER_SECURITY] ADD  CONSTRAINT [DF_USER_SECURITY_ADMIN_FLAG]  DEFAULT ((0)) FOR [ADMIN_FLAG]
GO

