USE [Media]
GO

/****** Object:  Table [MP3].[USER_SELECTION]    Script Date: 3/16/2017 08:05:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [MP3].[USER_SELECTION](
	[USER_SECURITY_ID] [numeric](38, 0) NOT NULL,
	[SONG_ID] [numeric](38, 0) NOT NULL,
	[CREATE_DATE] [datetime] NOT NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_USER_SELECTION] PRIMARY KEY CLUSTERED 
(
	[USER_SECURITY_ID] ASC,
	[SONG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [MP3].[USER_SELECTION] ADD  CONSTRAINT [DF_USER_SELECTION_CREATE_DATE]  DEFAULT (getdate()) FOR [CREATE_DATE]
GO

ALTER TABLE [MP3].[USER_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_USER_SELECTION_SONG] FOREIGN KEY([SONG_ID])
REFERENCES [MP3].[SONG] ([SONG_ID])
GO

ALTER TABLE [MP3].[USER_SELECTION] CHECK CONSTRAINT [FK_USER_SELECTION_SONG]
GO

ALTER TABLE [MP3].[USER_SELECTION]  WITH CHECK ADD  CONSTRAINT [FK_USER_SELECTION_USER_SECURITY] FOREIGN KEY([USER_SECURITY_ID])
REFERENCES [MP3].[USER_SECURITY] ([USER_SECURITY_ID])
GO

ALTER TABLE [MP3].[USER_SELECTION] CHECK CONSTRAINT [FK_USER_SELECTION_USER_SECURITY]
GO

