//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SECURITY
    {
        public decimal USER_SECURITY_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public bool LOCKED_FLAG { get; set; }
        public bool ACTIVE_FLAG { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public decimal LOGIN_FAILURE_COUNT { get; set; }
        public Nullable<System.DateTime> LAST_FAILURE_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public bool ADMIN_FLAG { get; set; }
        public Nullable<System.DateTime> PREV_TO_LAST_LOGIN_DATE { get; set; }
    }
}
